# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  python: circleci/python@2.0.3
commands:
  run_tests:
    steps:
        - checkout
        - run:
            name: Install
            command: pip install .[dev]
        - run:
            name: Run tests
            command: pytest tests/

jobs:
  test-3-11:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install
          command: |
            pip install .[dev]
            echo $HOME
      - run:
          name: Type checking
          command: mypy manifoldpy/
      - run:
          name: Run tests
          command: |
            pip install coverage
            coverage run -m pytest tests/
            coverage report
            coverage html --omit="tests/*"
      - store_artifacts:
          path: htmlcov
      - run:
          name: Upload coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov
  test-3-9:
    docker:
      - image: circleci/python:3.9
    steps:
      - run_tests
  test-3-8:
    docker:
      - image: circleci/python:3.8
    steps:
      - run_tests

workflows:
  build_and_test-workflow:
    jobs:
      - test-3-10
      - test-3-9
      - test-3-8
